version: '3.0'

services:
 angular: 
  build: test
  ports:
   - "4200:4200"
  volumes:
   - /usr/app/test/node_modules
   - ./test:/usr/app/test
   
 mongodb:
  image: mongo
  ports:
   - "27017:27017"
   
 mongo-seed:
  build: ./test-mongo-seed
  links:
    - mongodb

 express:
  build: test-service
  ports:
   - "3000:3000"
  volumes:
   - /usr/app/test-service/node_modules
   - ./test-service:/usr/app/test-service
  links:
   - mongodb
